### ISSUE TITLE
fix: single-level file output when `**/*.qsps` pattern and directory are specified

### ISSUE THREAD

**Issue by gretmn102** [QSPFoundation/qsp-cli#7]
## Description problem

Usage `qsp/cli@1.0.2` with `--directory`:

```bash
qsp-cli --directory output src/**/*.qsps
```

Where the `src` directory contains:

```text
src
├── 0.1.qsps
├── 0.2.qsps
├── 1
│   ├── 1.1.qsps
│   └── 1.2.qsps
└── 2
    ├── 1
    │   └── 2.1.1.qsps
    └── 2.1.qsps
```

Leads to a result:

```text
output
├── 0.1.qsp
├── 0.2.qsp
├── 1.1.qsp
├── 1.2.qsp
├── 2.1.1.qsp
└── 2.1.qsp
```

But it should:

```text
output
├── 0.1.qsp
├── 0.2.qsp
├── 1
│   ├── 1.1.qsp
│   └── 1.2.qsp
└── 2
    ├── 1
    │   └── 2.1.1.qsp
    └── 2.1.qsp
```

As it happens in:

```bash
qsp-cli src/**/*.qsps
```

## Repro steps

* create a nested file structure:

  ```bash
  mkdir src
  touch src/0.1.qsps
  touch src/0.2.qsps
  mkdir src/1
  touch src/1/1.1.qsps
  touch src/1/1.2.qsps
  mkdir src/2
  touch src/2/2.1.qsps
  mkdir src/2/1
  touch src/2/1/2.1.1.qsps
  ```

* install cli:

  ```bash
  npm i -g @qsp/cli@1.0.2
  ```

* run:

  ```bash
  qsp-cli --directory output src/**/*.qsps
  ```

  > ⚠️ warning
  >
  > Oh yes, if you use `**/*` in Bash 4+, you need to enable `globstar`:
  >
  > ```bash
  > shopt -s globstar
  > ```
  >
  > Otherwise wildcard pattern behaves incorrectly. This is probably why the `-r` flag is preferred more than the recursive glob wildcard.
  >
  > In `cmd` and `npm` script it works as expected.

* print:

  ```bash
  tree output
  ```

**Comment by srg-kostyrko** [comment]
this was fixed in 1.0.3
please pay attention that whole structure is kept inside output directory
so for this example - generated output will be
```
output
└ src
  ├── 0.1.qsp
  ├── 0.2.qsp
  ├── 1
  │   ├── 1.1.qsp
  │   └── 1.2.qsp
  └── 2
      ├── 1
      │   └── 2.1.1.qsp
      └── 2.1.qsp
```
